# .goreleaser.yml
version: 2

builds:
  - binary: ecs-tool
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  - vendor: Springload
    homepage: https://springload.co.nz

    maintainer: DevOps team
    description: Runs commands on ECS cluster
    license: Apache 2.0
    formats:
      - deb
      - rpm

brews:
  - name: ecs-tool
    tap:
      owner: springload
      name: homebrew-tools
    folder: Formula

