name: Build and publish ecs-tool
on:
  push:
    tags:
      - '*'
jobs:
  build_and_publish:
    name: build and publish ecs-tool
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed for tags
      -
        name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
